dhis2/data-administration-app

i18n/translations.pot, src/components/app-router/AppRouter.js, src/pages/Page.js, src/pages/Page.test.js, src/pages/data-integrity/DataIntegrity.js, src/pages/data-statistics/DataStatistics.js, src/pages/home/Home.js, src/pages/lock-exception/LockException.js, src/pages/maintenance/Maintenance.js, src/pages/min-max-value-generation/MinMaxValueGeneration.js
@MDHomem could you review it and approve if everything is ok.
=> code clean up

i18n/translations.pot, src/pages/data-statistics/DataStatistics.js, src/pages/data-statistics/data.statics.conf.js
=> Data Statistics labels

i18n/translations.pot, src/pages/lock-exception/LockException.css, src/pages/lock-exception/LockException.js, src/pages/lock-exception/LockException.test.js, src/pages/lock-exception/lock.exception.conf.js
@MDHomem review it please.
This PR needs server side developments [here](https://github.com/dhis2/dhis2-core/pull/1643).
=> Batch Deletion at Lock Exception Management

i18n/translations.pot, src/pages/lock-exception/LockException.js
@MDHomem review it please. After merging you can deploy it.
To solve this [issue](http://jira.cadsh.com/browse/DHIS2OUT-66).
=> Block Add Lock Exception options

e2e/pages/dhis2.page.js, e2e/pages/home.page.js, e2e/step-definitions/help.steps.js, i18n/translations.pot, package.json, src/components/page-helper/PageHelper.js, yarn.lock
@MDHomem review it and merge please.
=> End to end tests updated

e2e/features/dataIntegrity.feature, e2e/features/lockException.feature, e2e/features/minMaxValueGeneration.feature
Updated according to new button on dataIntegrity
Removed option to select several checkboxes on MinMax Value generation
=> New button and some fixes

src/i18n.js, src/pages/data-integrity/data.integrity.conf.js
Fixes https://jira.dhis2.org/browse/DHIS2-6078
Verified:
=> chore: add new integrity checks

src/i18n.js, src/pages/data-integrity/data.integrity.conf.js
See also: https://github.com/dhis2/data-administration-app/pull/54
=> fix: add translations for new integrity checks

src/i18n.js, src/pages/data-integrity/DataIntegrity.js, src/pages/data-integrity/data.integrity.conf.js
This is a forward-port of #461 which is already in `patch/2.35.0`
=> fix: add programIndicatorsWithNoExpression integrity check, avoid crash (DHIS2-9702) [2.35]

src/i18n.js, src/pages/data-integrity/DataIntegrity.js, src/pages/data-integrity/data.integrity.conf.js
This is a forward-port to 2.36 of #461
=> fix: add programIndicatorsWithNoExpression integrity check, avoid crash (DHIS2-9702) [2.36]

d2.config.js, package.json, yarn.lock
Related to [DHIS2-9893](https://jira.dhis2.org/browse/DHIS2-9893)
=> feat: upgrade to @dhis2/ui v6 and bump other dependency versions

.github/workflows/dhis2-verify-app.yml
Fixes https://jira.dhis2.org/browse/DHIS2-10700
=> ci: update workflows and fix build dir

src/pages/home/Home.js, src/pages/home/grid-section/GridSection.module.css, src/pages/home/grid.css
v36 backport of https://github.com/dhis2/data-administration-app/pull/598
=> fix: restore grid layout (v36)

src/pages/home/Home.js, src/pages/home/grid-section/GridSection.module.css, src/pages/home/grid.css
2.36.0 backport of https://github.com/dhis2/data-administration-app/pull/598
=> fix: restore grid layout (2.36.0)

src/pages/lock-exception/LockException.js
This was a very weird component and this is quite a weird fix, I'll try to add some comments in the code to clarify.
=> fix(lock-exception): address item removal bugs

src/pages/lock-exception/LockException.js
Closes https://jira.dhis2.org/browse/DHIS2-10899
=> fix: close add lock exception dialog after successful API call 

src/pages/lock-exception/LockException.js
v36 backport of https://github.com/dhis2/data-administration-app/pull/610
=> fix: close add lock exception dialog after successful API call (v36)

src/pages/lock-exception/LockException.js
Fixed DHIS2-10914
Backport for #612
=> fix(lock exception): keep pager in state when navigating to batch delete

src/pages/maintenance/Maintenance.js
Closes https://jira.dhis2.org/browse/DHIS2-10888
=> fix: use vertical layout for maintenance section

src/pages/maintenance/Maintenance.js
v36 backport of https://github.com/dhis2/data-administration-app/pull/619
=> fix: use vertical layout for maintenance section (v36)

i18n/en.pot, src/i18n.js
Closes https://jira.dhis2.org/browse/DHIS2-11241.
=> fix: pass i18n keys string literals to i18n.t to allow app platform to extract them (v36)

i18n/en.pot, src/i18n.js, src/pages/lock-exception/LockException.test.js
Closes https://jira.dhis2.org/browse/DHIS2-11241
=> fix: pass i18n keys string literals to i18n.t to allow d2-i18n-generate to extract them (v35)

i18n/en.pot, src/i18n.js, src/pages/lock-exception/LockException.test.js
Closes https://jira.dhis2.org/browse/DHIS2-11241
=> fix: pass i18n keys string literals to i18n.t to allow d2-i18n-generate to extract them (v34)

i18n/en.pot, src/pages/data-integrity/DataIntegrity.js, src/pages/data-integrity/data-integrity-card/DataIntegrityCard.js, src/pages/data-integrity/data-integrity-card/DataIntegrityCard.module.css
Closes https://jira.dhis2.org/browse/DHIS2-10985
This issue was already fixed in `master` and so this PR replaces `DataIntegrityCard.js` with its `master` version.
=> fix(data-integrity): do not indicate errors when none exist (v36)

cypress/integration/analytics-tables/index.js, cypress/integration/min-max-value-generation/index.js, cypress/integration/min-max-value-generation/user-deletes-min-max-values.js, cypress/integration/min-max-value-generation/user-generates-min-max-values.js, cypress/integration/resource-tables/index.js, src/pages/min-max-value-generation/MinMaxValueGeneration.js, src/pages/min-max-value-generation/MinMaxValueGeneration.module.css
Closes https://jira.dhis2.org/browse/DHIS2-11250
=> refactor: use MultiSelectField instead of <select>

src/pages/data-statistics/parse-tables.js
Closes https://jira.dhis2.org/browse/DHIS2-10785
- Sort objects by label
- Add i18n key for `eventVisualization` object type
=> fix(data-statistics): sort objects by label

i18n/en.pot, src/i18n.js, src/pages/data-statistics/DataStatistics.js
v35 backport of https://github.com/dhis2/data-administration-app/pull/723
=> fix(data-statistics): render unlabeled rows (v35)

src/hooks/use-poll.js
v38 backport of https://github.com/dhis2/data-administration-app/pull/761
=> fix: always use latest refetch from useDataQuery using ref (v38)

src/i18n-keys.js, src/pages/analytics/analytics.conf.js
See [DHIS2-13916](https://dhis2.atlassian.net/browse/DHIS2-13916)
**Before:**
**After:**
[DHIS2-13916]: https://dhis2.atlassian.net/browse/DHIS2-13916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add skipOrgUnitOwnership checkbox [DHIS2-13916]

src/i18n-keys.js, src/pages/analytics/analytics.conf.js
v39 backport of https://github.com/dhis2/data-administration-app/pull/900
=> fix: add skipOrgUnitOwnership checkbox [DHIS2-13916] (#900)

i18n/en.pot, src/pages/lock-exceptions/LockExceptions.js, src/pages/lock-exceptions/LockExceptions.module.css
=> fix(lock exception): remove text underline from top-right buttons

i18n/en.pot, src/pages/data-statistics/parse-tables.js
Backport of https://github.com/dhis2/data-administration-app/pull/1013
=> fix: remove duplicate counts [DHIS2-15948] (v40)

i18n/en.pot, src/pages/data-statistics/parse-tables.js
Reverts dhis2/data-administration-app#1024
(I added a v40 backport for this issue https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15948, but the change should have only applied v40+. Sorry 😔)
=> fix: remove duplicate counts [DHIS2-15948] (v40) [REVERT]

src/components/DocsLink/DocsLink.js
v39 backport of https://github.com/dhis2/data-administration-app/pull/1074
=> fix: reference master docs [DHIS2-16445] (v39)

src/pages/maintenance/Maintenance.js
v40 backport of https://github.com/dhis2/data-administration-app/pull/1059
=> fix: force current params [DHIS2-17758] (v40)

cypress/integration/maintenance/index.js, src/i18n-keys.js
Fixes: https://dhis2.atlassian.net/browse/DHIS2-18899
Note that we may want to update the label as well.
=> fix(maintenance): update deprecated reference to deprecated softDeletedTrackedEntityInstanceRemoval
