dhis2/data-administration-app

README.md, package.json, yarn.lock
Reasons for the ignores:
- `"@dhis2/d2-ui-header-bar"`: breaks when using latest. Not sure what changed (couldn't find a changelog, leaving it for now)
- `"d2"`: suspect this is a complicated upgrade, leaving this as well
- `"rxjs"`: updating to `rxjs@6` or removing it breaks tests due to the headerbar relying on it.
E2e test dependencies, not sure if they still work:
- `"cucumber"`
- `"wdio-allure-reporter"`
- `"wdio-selenium-standalone-service"`
- `"webdriverio"`
I say we tackle that separately as well.
=> Finalize adding greenkeeper

src/components/notifications-table/NotificationsTable.js, src/components/notifications-table/style.css, src/pages/analytics/Analytics.js, src/pages/resource-tables/ResourceTables.js
There has been an API change:
PRE: Calls to `system/tasks/{task-category-id}` would return an object with `jobId` keys, and the app would check if there was an active job
POST: Calls to `system/tasks/{task-category-id}` only return something if there is an active job. The app just assumes that is the only active job around.
So due to this API change I have removed the part of the code dealing with `jobId` in the analytics table and resource-tables section.
However, there was also something fishy going on with the NotificationTable (i.e. the "activity log"). I'm not sure whether this was also a result of an API change or if this always worked like this:
- Every task has a `completed` property
- But only the last task ever gets to have that property set to true, and this indicates that the …
=> Dhis2 7223 analytics run never reported finished

src/pages/analytics/Analytics.js, src/pages/resource-tables/ResourceTables.js
Small addition to the work I did earlier. I did not experience this problem locally, but remotely, you sometimes get back an empty array when calling the tasks endpoint. This also means there are no active jobs.
=> fix: no active jobs when empty array is returned

src/i18n.js, src/pages/data-integrity/DataIntegrity.js, src/pages/data-integrity/data.integrity.conf.js
This adds the missing `programIndicatorsWithNoExpression` integrity check.  It also avoids an `undefined` reference crash if an integrity check is found which doesn't have a locally-defined representation.
Notes:
1. The translations for the label will need to be added later (it's not clear how that's done in this app... if at all)
2. It would be better to show the integrity check failure even if it's not found in the local code
3. There's unnecessary duplication (and superfluous `.text` references which don't exist) between `DataIntegrity.conf.js` and `i18n.js`, but I decided not to refactor that here.
=> fix: add programIndicatorsWithNoExpression integrity check, avoid crash [DHIS2-9702]

src/pages/lock-exception/LockException.js
Fixes DHIS2-10914
When displaying the batch deletion page, the pager object was removed from the app state, which caused the bug.
I added the pager to the app state when clicking on the batch delete button
=> fix(lock exception): keep pager in state when navigating to batch delete

src/pages/lock-exception/AddLockExceptionForm.js
The [schema of the data sets API was changed accidentally](https://jira.dhis2.org/browse/DHIS2-11198), resulting in the `periodType` field changing from being a string to an object of shape `{ name: String }`.
Now that [the issue  has been fixed](https://github.com/dhis2/dhis2-core/pull/8162), the temporary client-side fix can be reverted.
=> fix: revert data sets API periodType schema fix

src/components/NotificationsTable/NotificationsTable.js, src/get-active-task-id-from-summary.js, src/hooks/use-poll.js, src/pages/analytics/Analytics.js, src/pages/analytics/use-analytics-poll.js, src/pages/resource-tables/ResourceTables.js, src/pages/resource-tables/use-resource-tables-poll.js
Closes https://jira.dhis2.org/browse/DHIS2-11560
Also fixes an issue where the parameters of the analytics task (e.g. `Skip generation of resource tables`) were set to true even if the user had not checked the associated checkbox.
=> fix: show progress of existing analytics and resource tables tasks

src/hooks/use-poll.js
When the `refetch` method of a `useDataQuery` is called, the associated data is set to null until the new request resolves.
This causes flickering in the analytics and resource tables pages as the data polled from the tasks endpoints is used to render a table showing the progress of the task.
=> fix: cache poll responses to prevent flickering

package.json, yarn.lock
Previous versions need their app-scripts and runtime versions bumped to introduce a service worker killswitch, as described in https://jira.dhis2.org/browse/DHIS2-11821. There was one PR on master some time ago (#693), but another one is made now to use the latest versions since then which include more fixes.
master and v38 will use cli-app-scripts ^v8 and app-runtime ^v3, and previous versions will use cli ^v7 and app-runtime ^v2 which have the same PWA fixes but won’t require a major version bump.
=> fix(deps): bump cli-app-scripts and app-runtime for pwa fixes

package.json, yarn.lock
Backport of https://github.com/dhis2/data-administration-app/pull/750 (but with different versions; more similar to #752):
Previous versions need their app-scripts and runtime versions bumped to introduce a service worker killswitch, as described in https://jira.dhis2.org/browse/DHIS2-11821. There was one PR on master some time ago (#693), but another one is made now to use the latest versions since then which include more fixes.
master and v38 will use cli-app-scripts ^v8 and app-runtime ^v3, and previous versions will use cli ^v7 and app-runtime ^v2 which have the same PWA fixes but won’t require a major version bump.
=> fix: upgrade app-scripts&runtime to use SW killswitch (v36)

package.json, yarn.lock
Backport of #750 
Previous versions need their app-scripts and runtime versions bumped to introduce a service worker killswitch, as described in https://jira.dhis2.org/browse/DHIS2-11821. There was one PR on master some time ago (#693), but another one is made now to use the latest versions since then which include more fixes.
master and v38 will use cli-app-scripts ^v8 and app-runtime ^v3, and previous versions will use cli ^v7 and app-runtime ^v2 which have the same PWA fixes but won’t require a major version bump.
=> fix(deps): bump cli-app-scripts and app-runtime for pwa fixes (v38)

package.json, yarn.lock
Backport of #750 (but with different versions):
Previous versions need their app-scripts and runtime versions bumped to introduce a service worker killswitch, as described in https://jira.dhis2.org/browse/DHIS2-11821. There was one PR on master some time ago (#693), but another one is made now to use the latest versions since then which include more fixes.
master and v38 will use cli-app-scripts ^v8 and app-runtime ^v3, and previous versions will use cli ^v7 and app-runtime ^v2 which have the same PWA fixes but won’t require a major version bump.
=> fix: upgrade app-scripts&runtime to use SW killswitch (v37)

src/hooks/use-poll.js
Closes https://jira.dhis2.org/browse/DHIS2-12775
In https://github.com/dhis2/data-administration-app/pull/750, we bumped `@dhis2/app-runtime` to a version that included the changes made in https://github.com/dhis2/app-runtime/pull/1086. The changes from the latter PR mean that it is no longer safe (in the sense that `refetch` does not behave as expected) to assume that the `refetch` function returned by a `useDataQuery` hook will be constant thoughout the lifetime of a component.
This assumption has been fixed by having the `useLazyInterval` hook assume that its first argument (the function to run in the interval) can change.
=> fix: always use latest refetch from useDataQuery using ref

src/components/NotificationsTable/NotificationsTable.js, src/components/NotificationsTable/NotificationsTable.module.css
Fixes [DHIS2-13118](https://jira.dhis2.org/browse/DHIS2-13118). Also see [this](https://dhis2.slack.com/archives/CPGUFVC56/p1650455935436329) Slack thread.
The issue was not caused by long log messages per se, but very long "words" i.e. sequences of characters not interrupted by spaces. So to resolve it I had to resort to wrapping the message in a `span` with `word-break: break-word;`. Things would now look like this:
=> fix(analytics-tables): prevent excessive table width for long strings

i18n/en.pot, src/pages/lock-exceptions/LockExceptions.js, src/pages/lock-exceptions/LockExceptions.module.css
Backports: #905 
Before:
After:
=> fix(lock exception): remove text underline from top-right buttons

src/pages/sections.conf.js
simple change to align with recent changes to docs.
This is not very important, but it is zero risk, and it closes an issue raised in beta testing.
=> fix: align docs section with updates to master docs [BETA-24]

src/pages/analytics/analytics.conf.js
In `dhis-web-data-administration/index.html#/analytics`, there is a dropdown for "Number of last years of data to include".  It starts at 1, but 0 is a valid value that leads to calculating analytics for all changed values since the last analytics update.
This PR adds that value to the menu.
=> fix: last years missing valid value of 0

i18n/en.pot, src/i18n-keys.js, src/pages/resource-tables/ResourceTables.js, src/pages/sections.conf.js
This is essentially a backport of https://github.com/dhis2/data-administration-app/pull/1055
Note that in v40, the table names are in the "old" format (`_orgunitstructure`, not `analytics_rs_orgunitstructure`). 
Corresponds to this documentation PR: https://github.com/dhis2/dhis2-docs/pull/1415
=> fix: clean up resource tables page [DHIS2-16445] v40

i18n/en.pot, src/i18n-keys.js, src/pages/resource-tables/ResourceTables.js, src/pages/sections.conf.js
This is essentially a backport of https://github.com/dhis2/data-administration-app/pull/1055
Note that in v39, the table names are in the "old" format (`_orgunitstructure`, not `analytics_rs_orgunitstructure`). Also note that documentation links direct you to current version's docs, but I believe this is by design as eventually the docs for older versions can be removed (I think I asked Phil about this once before).
Corresponds to this documentation PR: https://github.com/dhis2/dhis2-docs/pull/1414
=> fix: clean up resources page [DHIS2-16445] v39

src/pages/maintenance/Maintenance.js
See https://dhis2.atlassian.net/browse/DHIS2-17758
The issue here was that previous selections under Maintenance page were persisted in query even after you unclicked them. E.g. if you selected "Prune periods", executed the query, then selected "Removed expired invitations" and unclicked "Prune periods", the query would be api/maintenance?prunePeriods=true&expiredInvitationsClear=true.
This is caused by logic in app-runtime whereby variables on subsequent mutation executions are added to the previous variables: https://github.com/dhis2/app-runtime/blob/master/services/data/src/react/hooks/useQueryExecutor.ts#L58-L61.
I don't know the reasoning behind that logic (i.e. it might be by design), so for now, I am fixing the immediate issue in the app by passing `params` as an object to …
=> fix: force current params [DHIS2-17758]

src/components/DocsLink/DocsLink.js
This PR sets the links used in the data administration app to always reference the `master` version.
From Phil:
> Yes, as long as we reference central documentation it is best to reference the master version.
Lina noticed that the link was inconsistent when reviewing the original ticket (https://dhis2.atlassian.net/browse/DHIS2-16445?focusedCommentId=200012).
=> fix: reference master docs [DHIS2-16445]

src/components/DocsLink/DocsLink.js
v40 backport of https://github.com/dhis2/data-administration-app/pull/1074
=> fix: reference master docs [DHIS2-16445] (v40)
